/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next/esm')['Aside']
    TBadge: typeof import('tdesign-vue-next/esm')['Badge']
    TButton: typeof import('tdesign-vue-next/esm')['Button']
    TContent: typeof import('tdesign-vue-next/esm')['Content']
    TDivider: typeof import('tdesign-vue-next/esm')['Divider']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    TIcon: typeof import('tdesign-vue-next/esm')['Icon']
    TLayout: typeof import('tdesign-vue-next/esm')['Layout']
    TMenu: typeof import('tdesign-vue-next/esm')['Menu']
    TMenuItem: typeof import('tdesign-vue-next/esm')['MenuItem']
    TProgress: typeof import('tdesign-vue-next/esm')['Progress']
    TTable: typeof import('tdesign-vue-next/esm')['Table']
    TTag: typeof import('tdesign-vue-next/esm')['Tag']
    VChart: typeof import('vue-echarts')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
