/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next/esm')['Button']
    TContent: typeof import('tdesign-vue-next/esm')['Content']
    TDivider: typeof import('tdesign-vue-next/esm')['Divider']
    TForm: typeof import('tdesign-vue-next/esm')['Form']
    TFormItem: typeof import('tdesign-vue-next/esm')['FormItem']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    TInput: typeof import('tdesign-vue-next/esm')['Input']
    TLayout: typeof import('tdesign-vue-next/esm')['Layout']
    TProgress: typeof import('tdesign-vue-next/esm')['Progress']
    TSpace: typeof import('tdesign-vue-next/esm')['Space']
    TTable: typeof import('tdesign-vue-next/esm')['Table']
    TTag: typeof import('tdesign-vue-next/esm')['Tag']
    VChart: typeof import('vue-echarts')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
