/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'echarts': RouteRecordInfo<'echarts', '/echarts', Record<never, never>, Record<never, never>>,
    'playground': RouteRecordInfo<'playground', '/playground', Record<never, never>, Record<never, never>>,
    'tailwind': RouteRecordInfo<'tailwind', '/tailwind', Record<never, never>, Record<never, never>>,
    'tdesign': RouteRecordInfo<'tdesign', '/tdesign', Record<never, never>, Record<never, never>>,
    'VueQuery': RouteRecordInfo<'VueQuery', '/vuequery', Record<never, never>, Record<never, never>>,
    'VueUse': RouteRecordInfo<'VueUse', '/vueuse', Record<never, never>, Record<never, never>>,
  }
}
